<?php

declare(strict_types=1);

/**
 * Generates config/countries.php from resources/data/iso3166.json.
 * Run: php scripts/generate-countries-config.php
 */

$root = dirname(__DIR__);
$source = $root.'/resources/data/iso3166.json';
$target = $root.'/config/countries.php';

if (! is_file($source)) {
    fwrite(STDERR, "Missing source file: {$source}\n");
    exit(1);
}

/** @var list<array{name: string, alpha-2: string}> $rows */
$rows = json_decode((string) file_get_contents($source), true, 512, JSON_THROW_ON_ERROR);

$aliases = [
    'United Kingdom of Great Britain and Northern Ireland' => 'United Kingdom',
    'United States of America' => 'United States',
    'Russian Federation' => 'Russia',
    'Iran, Islamic Republic of' => 'Iran',
    'Korea, Republic of' => 'South Korea',
    "Korea, Democratic People's Republic of" => 'North Korea',
    'Venezuela, Bolivarian Republic of' => 'Venezuela',
    'Bolivia, Plurinational State of' => 'Bolivia',
    'Viet Nam' => 'Vietnam',
    'Taiwan, Province of China' => 'Taiwan',
    'Congo, Democratic Republic of the' => 'Congo - Kinshasa',
    'Congo' => 'Congo - Brazzaville',
    'Tanzania, United Republic of' => 'Tanzania',
    'Moldova, Republic of' => 'Moldova',
    'Micronesia, Federated States of' => 'Micronesia',
    'Lao People\'s Democratic Republic' => 'Laos',
    'Syrian Arab Republic' => 'Syria',
    'Netherlands, Kingdom of the' => 'Netherlands',
    'Palestine, State of' => 'Palestine',
];

$names = [];

foreach ($rows as $row) {
    $code = strtoupper((string) ($row['alpha-2'] ?? ''));
    $name = trim((string) ($row['name'] ?? ''));

    if ($code === '' || $name === '') {
        continue;
    }

    $names[$code] = $aliases[$name] ?? $name;
}

asort($names, SORT_NATURAL | SORT_FLAG_CASE);

$export = var_export($names, true);
$contents = <<<PHP
<?php

declare(strict_types=1);

/**
 * ISO 3166-1 alpha-2 country names (English).
 * Generated by scripts/generate-countries-config.php — do not edit manually.
 */
return [
    'names' => {$export},
];

PHP;

file_put_contents($target, $contents);

echo 'Wrote '.count($names).' countries to '.$target.PHP_EOL;
