apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  namespace: factory23
  labels:
    app.kubernetes.io/name: realtime
    app.kubernetes.io/component: websocket
spec:
  type: ClusterIP
  selector:
    app: realtime
  ports:
    - name: ws
      port: 8081
      targetPort: 8081
      protocol: TCP
